### ISSUE TITLE
`fromPrincipal` returns only 28 bytes, which isn't a valid account identifier

### ISSUE THREAD

**Issue by jorgenbuilder** [aviate-labs/principal.mo#1]
## Expected Behavior

I believe the `AccountIdentifier` strictly requires 32 bytes, and any methods that intend to generate this type should always include all 32 bytes.

## Actual Behavior

`AccountIdentifier.fromPrincipal` generates 28 bytes without the 4 byte hash. I found that this was an issue when trying to interact with the NNS ledger with `AccountIdentifier`s generated by this library.

## Version

v0.2.5

**Comment by q-uint** [comment]
I would recommend you use the `blob` subpackage, there the CRC hash gets added automatically.
